// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    FreeIcon: typeof import('./src/components/free-icon')['default']
  }
}

export { }


declare interface Config{
   TOKEN_NAME: string
}
